"""Tests for ToolCallEvent and ToolReturnEvent emission from ContextManager.

Covers FR-TCE-8: event emission logic for all tool-related message part kinds.
Story 2.4: Adds run_id assertions to all tool event tests.

Note: Uses the same importlib loading pattern as test_context.py to avoid
pulling in the providers dependency (pydantic-ai providers require API keys
at import time in some configurations). ToolCallEvent / ToolReturnEvent are
imported directly from akgentic.llm because they have no providers transitive dep.
"""

import importlib.util
import uuid
from datetime import datetime
from pathlib import Path

from pydantic_ai.messages import (
    ModelRequest,
    ModelResponse,
    RetryPromptPart,
    TextPart,
    ToolCallPart,
    ToolReturnPart,
    UserPromptPart,
)

# Load context module via importlib to avoid providers transitive dependency
_CONTEXT_PATH = Path(__file__).parent.parent / "src" / "akgentic" / "llm" / "context.py"
_spec = importlib.util.spec_from_file_location("context", _CONTEXT_PATH)
_context_module = importlib.util.module_from_spec(_spec)  # type: ignore[arg-type]
_spec.loader.exec_module(_context_module)  # type: ignore[union-attr]

ContextManager = _context_module.ContextManager

# Import event classes directly — no providers dep in event.py
from akgentic.llm.event import LlmMessageEvent, ToolCallEvent, ToolReturnEvent  # noqa: E402, I001

# Canonical run_id used throughout these tests (AC-5, AC-6)
RUN_ID = uuid.UUID("cf92c35f-4ee9-4cff-8361-b8ce3827e021")
RUN_ID_STR = str(RUN_ID)

# A second distinct run_id for multi-run isolation checks
RUN_ID_B = uuid.UUID("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee")
RUN_ID_B_STR = str(RUN_ID_B)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


class EventCapture:
    """Captures all domain events in emission order."""

    def __init__(self) -> None:
        self.events: list[object] = []

    def notify_event(self, event: object) -> None:
        """Append each received event for ordered assertion."""
        self.events.append(event)


def _make_manager_with_capture() -> tuple[ContextManager, EventCapture]:
    """Return a ContextManager wired to an EventCapture observer."""
    manager = ContextManager()
    capture = EventCapture()
    manager.subscribe(capture)
    return manager, capture


def _tool_call_msg(
    tool_name: str = "web_search_tool",
    tool_call_id: str = "call_abc123",
    args: str = '{"query": "test"}',
    run_id: uuid.UUID = RUN_ID,
) -> ModelResponse:
    return ModelResponse(
        parts=[ToolCallPart(tool_name=tool_name, tool_call_id=tool_call_id, args=args)],
        timestamp=datetime.now(),
        run_id=run_id,
    )


def _tool_return_msg(
    tool_name: str = "web_search_tool",
    tool_call_id: str = "call_abc123",
    content: str = "search results here",
    run_id: uuid.UUID = RUN_ID,
) -> ModelRequest:
    return ModelRequest(
        parts=[ToolReturnPart(tool_name=tool_name, tool_call_id=tool_call_id, content=content)],
        run_id=run_id,
    )


def _retry_with_id_msg(
    tool_name: str = "web_search_tool",
    tool_call_id: str = "call_abc123",
    content: str = "Tool raised error",
    run_id: uuid.UUID = RUN_ID,
) -> ModelRequest:
    return ModelRequest(
        parts=[
            RetryPromptPart(tool_name=tool_name, tool_call_id=tool_call_id, content=content)
        ],
        run_id=run_id,
    )


def _retry_no_tool_name_msg(
    content: str = "Please retry in the correct format.",
    run_id: uuid.UUID = RUN_ID,
) -> ModelRequest:
    """Return a RetryPromptPart with tool_name=None (non-tool retry).

    Note: tool_call_id is always auto-generated by pydantic-ai (never None).
    The discriminator for tool vs. non-tool retry-prompts is tool_name, not tool_call_id.
    """
    return ModelRequest(parts=[RetryPromptPart(content=content)], run_id=run_id)


def _text_msg(
    content: str = "Hello world",
    run_id: uuid.UUID = RUN_ID,
) -> ModelResponse:
    return ModelResponse(
        parts=[TextPart(content=content)],
        timestamp=datetime.now(),
        run_id=run_id,
    )


# ---------------------------------------------------------------------------
# AC-2 / AC-5: single tool-call part — run_id propagated
# ---------------------------------------------------------------------------


class TestSingleToolCall:
    """AC-2 / AC-5: single tool-call part → LlmMessageEvent then ToolCallEvent with run_id."""

    def test_lmm_message_event_emitted_first(self) -> None:
        """LlmMessageEvent must precede ToolCallEvent."""
        manager, capture = _make_manager_with_capture()
        msg = _tool_call_msg()
        manager.add_message(msg)

        assert len(capture.events) == 2
        assert isinstance(capture.events[0], LlmMessageEvent)
        assert isinstance(capture.events[1], ToolCallEvent)

    def test_llm_message_event_carries_correct_message(self) -> None:
        """LlmMessageEvent.message must be the message passed to add_message()."""
        manager, capture = _make_manager_with_capture()
        msg = _tool_call_msg()
        manager.add_message(msg)

        llm_event = capture.events[0]
        assert isinstance(llm_event, LlmMessageEvent)
        assert llm_event.message is msg

    def test_tool_call_event_fields(self) -> None:
        """ToolCallEvent fields must match the part's attributes."""
        manager, capture = _make_manager_with_capture()
        msg = _tool_call_msg(
            tool_name="my_tool",
            tool_call_id="call_xyz",
            args='{"param": "value"}',
        )
        manager.add_message(msg)

        event = capture.events[1]
        assert isinstance(event, ToolCallEvent)
        assert event.tool_name == "my_tool"
        assert event.tool_call_id == "call_xyz"
        assert event.arguments == '{"param": "value"}'

    def test_tool_call_event_run_id_equals_message_run_id(self) -> None:
        """AC-5: ToolCallEvent.run_id == str(message.run_id)."""
        manager, capture = _make_manager_with_capture()
        msg = _tool_call_msg(run_id=RUN_ID)
        manager.add_message(msg)

        event = capture.events[1]
        assert isinstance(event, ToolCallEvent)
        assert event.run_id == RUN_ID_STR


# ---------------------------------------------------------------------------
# AC-3 / AC-4: two tool-call parts in one response — shared run_id
# ---------------------------------------------------------------------------


class TestParallelToolCalls:
    """AC-3 / AC-4: two tool-call parts in one ModelResponse share the same run_id."""

    def test_two_tool_call_events_emitted_in_part_order(self) -> None:
        """Two ToolCallEvent instances emitted after LlmMessageEvent, in part order."""
        manager, capture = _make_manager_with_capture()
        msg = ModelResponse(
            parts=[
                ToolCallPart(tool_name="tool_a", tool_call_id="call_001", args='{"x": 1}'),
                ToolCallPart(tool_name="tool_b", tool_call_id="call_002", args='{"y": 2}'),
            ],
            timestamp=datetime.now(),
            run_id=RUN_ID,
        )
        manager.add_message(msg)

        assert len(capture.events) == 3
        assert isinstance(capture.events[0], LlmMessageEvent)
        assert isinstance(capture.events[1], ToolCallEvent)
        assert isinstance(capture.events[2], ToolCallEvent)

    def test_parallel_tool_events_correct_fields(self) -> None:
        """Each ToolCallEvent carries fields from its own part."""
        manager, capture = _make_manager_with_capture()
        msg = ModelResponse(
            parts=[
                ToolCallPart(tool_name="tool_a", tool_call_id="call_001", args='{"x": 1}'),
                ToolCallPart(tool_name="tool_b", tool_call_id="call_002", args='{"y": 2}'),
            ],
            timestamp=datetime.now(),
            run_id=RUN_ID,
        )
        manager.add_message(msg)

        event_a = capture.events[1]
        event_b = capture.events[2]
        assert isinstance(event_a, ToolCallEvent)
        assert isinstance(event_b, ToolCallEvent)
        assert event_a.tool_name == "tool_a"
        assert event_a.tool_call_id == "call_001"
        assert event_a.arguments == '{"x": 1}'
        assert event_b.tool_name == "tool_b"
        assert event_b.tool_call_id == "call_002"
        assert event_b.arguments == '{"y": 2}'

    def test_parallel_tool_call_events_share_same_run_id(self) -> None:
        """AC-4: both ToolCallEvent instances from the same response carry the same run_id."""
        manager, capture = _make_manager_with_capture()
        msg = ModelResponse(
            parts=[
                ToolCallPart(tool_name="tool_a", tool_call_id="call_001", args='{"x": 1}'),
                ToolCallPart(tool_name="tool_b", tool_call_id="call_002", args='{"y": 2}'),
            ],
            timestamp=datetime.now(),
            run_id=RUN_ID,
        )
        manager.add_message(msg)

        event_a = capture.events[1]
        event_b = capture.events[2]
        assert isinstance(event_a, ToolCallEvent)
        assert isinstance(event_b, ToolCallEvent)
        assert event_a.run_id == RUN_ID_STR
        assert event_b.run_id == RUN_ID_STR
        assert event_a.run_id == event_b.run_id

    def test_two_consecutive_runs_carry_distinct_run_ids(self) -> None:
        """Events from different runs must carry different run_id values.

        Verifies that run_id reflects the originating message, not a shared state.
        """
        manager, capture = _make_manager_with_capture()
        msg_a = ModelResponse(
            parts=[ToolCallPart(tool_name="tool_x", tool_call_id="call_r1", args="{}")],
            timestamp=datetime.now(),
            run_id=RUN_ID,
        )
        msg_b = ModelResponse(
            parts=[ToolCallPart(tool_name="tool_x", tool_call_id="call_r2", args="{}")],
            timestamp=datetime.now(),
            run_id=RUN_ID_B,
        )
        manager.add_message(msg_a)
        manager.add_message(msg_b)

        tool_events = [e for e in capture.events if isinstance(e, ToolCallEvent)]
        assert len(tool_events) == 2
        assert tool_events[0].run_id == RUN_ID_STR
        assert tool_events[1].run_id == RUN_ID_B_STR
        assert tool_events[0].run_id != tool_events[1].run_id


# ---------------------------------------------------------------------------
# AC-4 / AC-6: tool-return part → ToolReturnEvent(success=True) with run_id
# ---------------------------------------------------------------------------


class TestToolReturn:
    """AC-4 / AC-6: tool-return part → ToolReturnEvent with success=True and run_id."""

    def test_tool_return_event_emitted(self) -> None:
        """ToolReturnEvent emitted after LlmMessageEvent for tool-return part."""
        manager, capture = _make_manager_with_capture()
        msg = _tool_return_msg()
        manager.add_message(msg)

        assert len(capture.events) == 2
        assert isinstance(capture.events[0], LlmMessageEvent)
        assert isinstance(capture.events[1], ToolReturnEvent)

    def test_tool_return_event_fields(self) -> None:
        """ToolReturnEvent carries correct fields and success=True."""
        manager, capture = _make_manager_with_capture()
        msg = _tool_return_msg(tool_name="my_tool", tool_call_id="call_xyz")
        manager.add_message(msg)

        event = capture.events[1]
        assert isinstance(event, ToolReturnEvent)
        assert event.tool_name == "my_tool"
        assert event.tool_call_id == "call_xyz"
        assert event.success is True

    def test_tool_return_event_run_id_equals_message_run_id(self) -> None:
        """AC-6: ToolReturnEvent.run_id == str(message.run_id) for a tool-return part."""
        manager, capture = _make_manager_with_capture()
        msg = _tool_return_msg(run_id=RUN_ID)
        manager.add_message(msg)

        event = capture.events[1]
        assert isinstance(event, ToolReturnEvent)
        assert event.run_id == RUN_ID_STR


# ---------------------------------------------------------------------------
# AC-5: retry-prompt with tool_call_id → ToolReturnEvent(success=False)
# ---------------------------------------------------------------------------


class TestRetryPromptWithId:
    """AC-5: retry-prompt with tool_call_id → ToolReturnEvent(success=False) with run_id."""

    def test_retry_prompt_with_id_emits_tool_return_event(self) -> None:
        """ToolReturnEvent(success=False) emitted for retry-prompt with tool_call_id."""
        manager, capture = _make_manager_with_capture()
        msg = _retry_with_id_msg(tool_name="my_tool", tool_call_id="call_xyz")
        manager.add_message(msg)

        assert len(capture.events) == 2
        assert isinstance(capture.events[0], LlmMessageEvent)
        assert isinstance(capture.events[1], ToolReturnEvent)

    def test_retry_prompt_with_id_event_fields(self) -> None:
        """ToolReturnEvent from retry-prompt has correct tool_call_id and success=False."""
        manager, capture = _make_manager_with_capture()
        msg = _retry_with_id_msg(tool_name="err_tool", tool_call_id="call_err")
        manager.add_message(msg)

        event = capture.events[1]
        assert isinstance(event, ToolReturnEvent)
        assert event.tool_name == "err_tool"
        assert event.tool_call_id == "call_err"
        assert event.success is False

    def test_retry_prompt_tool_return_event_run_id(self) -> None:
        """ToolReturnEvent from retry-prompt carries the message's run_id."""
        manager, capture = _make_manager_with_capture()
        msg = _retry_with_id_msg(run_id=RUN_ID)
        manager.add_message(msg)

        event = capture.events[1]
        assert isinstance(event, ToolReturnEvent)
        assert event.run_id == RUN_ID_STR


# ---------------------------------------------------------------------------
# Edge case: run_id=None → event.run_id == "None"
# ---------------------------------------------------------------------------


class TestRunIdNone:
    """Document the behaviour when message.run_id is None.

    pydantic-ai types run_id as str | None; str(None) == "None".
    Consumers that filter events by run_id must account for this sentinel.
    """

    def test_tool_call_event_run_id_is_none_string_when_message_run_id_is_none(self) -> None:
        """ToolCallEvent.run_id == 'None' when message.run_id is None."""
        manager, capture = _make_manager_with_capture()
        msg = ModelResponse(
            parts=[ToolCallPart(tool_name="t", tool_call_id="c", args="{}")],
            timestamp=datetime.now(),
            run_id=None,  # type: ignore[arg-type]
        )
        manager.add_message(msg)

        event = capture.events[1]
        assert isinstance(event, ToolCallEvent)
        assert event.run_id == str(None)  # "None"


# ---------------------------------------------------------------------------
# AC-6: retry-prompt without tool_call_id → no ToolReturnEvent
# ---------------------------------------------------------------------------


class TestRetryPromptWithoutToolName:
    """AC-6: retry-prompt with tool_name=None emits only LlmMessageEvent.

    Note: pydantic-ai auto-generates tool_call_id for all RetryPromptPart instances
    (it is never None). The discriminator for tool vs. non-tool retry-prompts is
    tool_name: None means a non-tool retry (e.g. output format validation failure).
    """

    def test_retry_prompt_no_tool_name_emits_only_llm_message_event(self) -> None:
        """Only LlmMessageEvent emitted — no ToolReturnEvent for non-tool retry."""
        manager, capture = _make_manager_with_capture()
        msg = _retry_no_tool_name_msg()
        manager.add_message(msg)

        assert len(capture.events) == 1
        assert isinstance(capture.events[0], LlmMessageEvent)

    def test_retry_prompt_no_tool_name_no_tool_return_event(self) -> None:
        """ToolReturnEvent must NOT appear in captured events."""
        manager, capture = _make_manager_with_capture()
        manager.add_message(_retry_no_tool_name_msg())

        tool_return_events = [e for e in capture.events if isinstance(e, ToolReturnEvent)]
        assert len(tool_return_events) == 0


# ---------------------------------------------------------------------------
# AC-7: text-only ModelResponse → no tool events
# ---------------------------------------------------------------------------


class TestTextOnlyResponse:
    """AC-7: text-only ModelResponse emits only LlmMessageEvent."""

    def test_text_only_emits_only_llm_message_event(self) -> None:
        """TextPart response produces exactly one LlmMessageEvent, no tool events."""
        manager, capture = _make_manager_with_capture()
        manager.add_message(_text_msg())

        assert len(capture.events) == 1
        assert isinstance(capture.events[0], LlmMessageEvent)

    def test_text_only_no_tool_events(self) -> None:
        """No ToolCallEvent or ToolReturnEvent emitted for text-only responses."""
        manager, capture = _make_manager_with_capture()
        manager.add_message(_text_msg())

        assert not any(isinstance(e, ToolCallEvent) for e in capture.events)
        assert not any(isinstance(e, ToolReturnEvent) for e in capture.events)


# ---------------------------------------------------------------------------
# AC-9: public API export
# ---------------------------------------------------------------------------


class TestPublicApiExport:
    """AC-9: ToolCallEvent and ToolReturnEvent importable from akgentic.llm."""

    def test_tool_call_event_importable_from_akgentic_llm(self) -> None:
        """ToolCallEvent must be importable from the top-level package."""
        import akgentic.llm as llm

        assert hasattr(llm, "ToolCallEvent")

    def test_tool_return_event_importable_from_akgentic_llm(self) -> None:
        """ToolReturnEvent must be importable from the top-level package."""
        import akgentic.llm as llm

        assert hasattr(llm, "ToolReturnEvent")

    def test_tool_call_event_in_all(self) -> None:
        """ToolCallEvent must appear in __all__."""
        import akgentic.llm as llm

        assert "ToolCallEvent" in llm.__all__

    def test_tool_return_event_in_all(self) -> None:
        """ToolReturnEvent must appear in __all__."""
        import akgentic.llm as llm

        assert "ToolReturnEvent" in llm.__all__

    def test_direct_import(self) -> None:
        """Direct named import from akgentic.llm must succeed."""
        from akgentic.llm import ToolCallEvent as ImportedToolCallEvent
        from akgentic.llm import ToolReturnEvent as ImportedToolReturnEvent

        assert ImportedToolCallEvent is ToolCallEvent
        assert ImportedToolReturnEvent is ToolReturnEvent


# ---------------------------------------------------------------------------
# Dataclass properties: frozen=True
# ---------------------------------------------------------------------------


class TestEventDataclassProperties:
    """Verify event dataclasses are frozen (immutable)."""

    def test_tool_call_event_is_frozen(self) -> None:
        """ToolCallEvent must be immutable (frozen=True)."""
        import dataclasses

        event = ToolCallEvent(run_id=RUN_ID_STR, tool_name="t", tool_call_id="c", arguments="{}")
        with __import__("pytest").raises(dataclasses.FrozenInstanceError):
            event.tool_name = "other"  # type: ignore[misc]

    def test_tool_return_event_is_frozen(self) -> None:
        """ToolReturnEvent must be immutable (frozen=True)."""
        import dataclasses

        event = ToolReturnEvent(run_id=RUN_ID_STR, tool_name="t", tool_call_id="c", success=True)
        with __import__("pytest").raises(dataclasses.FrozenInstanceError):
            event.success = False  # type: ignore[misc]


# ---------------------------------------------------------------------------
# User-prompt message (non-tool ModelRequest) → no tool events
# ---------------------------------------------------------------------------


class TestNonToolModelRequest:
    """A ModelRequest with a UserPromptPart should emit only LlmMessageEvent."""

    def test_user_prompt_emits_only_llm_message_event(self) -> None:
        """UserPromptPart in ModelRequest produces no tool events."""
        manager, capture = _make_manager_with_capture()
        msg = ModelRequest(parts=[UserPromptPart(content="Hello")])
        manager.add_message(msg)

        assert len(capture.events) == 1
        assert isinstance(capture.events[0], LlmMessageEvent)
